require 'middleman/s3_sync/version'
require 'middleman/s3_sync/caching_policy'
require 'middleman/s3_sync/status'
require 'middleman/s3_sync/resource'
require 'middleman/s3_sync/synchronizer'
require 'middleman-s3_sync/extension'
